### PR TITLE
New CEP on refactoring the refman.

### PR DESCRIPTION
**Pull request by Zimmi48**
This PR is for final validation before submitting on the official CEP repo.

### CODE REVIEW

**Comment by mattam82** [comment]
Ok with me, I hope we can gather enough support for the proposed change plan. Let's discuss it at the Call. Maybe it would be good to bring back the detailed outline of the first part (part of PR #11601) in the CEP for larger discussion?

**Comment by Zimmi48** [comment]
>Maybe it would be good to bring back the detailed outline of the first part (part of PR #11601)

I am not sure what you mean by this: coq/coq#11601 does not include a detailed outline for the first part, since it only moves existing chapters around. The non-detailed outline is already present in the CEP.

**Comment by mattam82** [comment]
I mean that maybe we should try to detail and settle this list before we discuss it so we have something concrete to start with and check with the larger audience that we're not missing anything, already in the CEP:

- Terms
- Typing
- Conversion
- Universe Polymorphism
- SProp
- CoInductives
- Native Integers
- VM and native compute
- Module system

**Comment by Zimmi48** [comment]
OK, so here's my proposal for this list:

- Terms
- Typing
- Conversion, including efficient reduction machines
- Non-recursive variants and records
- Inductive types and recursive functions
- Co-inductive types and co-recursive functions
- Sorts, including SProp
- Universes, including template polymorphism and full universe polymorphism
- Native integers, floats, etc.
- Sections
- Modules

But while I am fine with including such a list in the CEP, I'm afraid that we won't be able to provide such a detailed view for all the chapters, and that we will anyway need to refine it as we proceed.

**Comment by Zimmi48** [comment]
@mattam82 I've added such an outline. Let me know if that looks good to you. We can release this later today or tomorrow and discuss it in the call of next week.

**Pull request closed without merging**
